global:
  # metric 수집 주기
  scrape_interval: 5s

scrape_configs:
  - job_name: "coupon-api"
    # 해당 경로로 지표 수집
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: "coupon-consumer"
    # 해당 경로로 지표 수집
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']