spring:
  application:
    name: coupon-api
server:
  port: 8080
management:
  metrics:
    tags:
      application:
          ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus